# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

# Add Maintainer Info
LABEL maintainer="achievers.nitin@gmail.com@gmail.com"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8761 available to the world outside this container
EXPOSE 8761

# The application's jar file
ARG JAR_FILE=target/spring-cloud-eureka-0.0.1-SNAPSHOT

# Add the application's jar to the container
ADD ${JAR_FILE} spring-cloud-eureka-0.0.1-SNAPSHOT
# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/spring-cloud-eureka-0.0.1-SNAPSHOT"]