FROM openjdk:8-jdk-alpine
copy ./target/currency-conversion-service-0.0.1-SNAPSHOT.jar currency-conversion-service-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","currency-conversion-service-0.0.1-SNAPSHOT.jar"]